### ISSUE TITLE
where can i get "Crypto.Cipher"

### ISSUE THREAD

**Issue by syskeyed** [davidbaszucki/RobloxAccountGenerator#1]
i tried pip install crypto and pip install Crypto.Cipher but that didnt work

**Comment by davidbaszucki** [comment]
pip install pycryptodome

**Comment by yougotsyskeyed** [comment]
thanks, but now i get the error 
`    with open("fp.js") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'fp.js'`

**Comment by 3x71us1v3** [comment]
I get this issue as well, even though I've installed everything.

**Comment by TreKzr3D** [comment]
Locate your "site-packages" folder, and change the folder "crypto" to "Crypto"  (case sensitive)
