### ISSUE TITLE
not generating

### ISSUE THREAD

**Issue by sadlylegit** [davidbaszucki/RobloxAccountGenerator#5]
so it wont generate any accounts is it my proxies?

**Comment by Eevvaann6** [comment]
same got it to work finally

**Comment by sadlylegit** [comment]
hmmm

**Comment by sadlylegit** [comment]
i got it working but no accounts are generating i only get f's

**Comment by Eevvaann6** [comment]
For me i get nothing from the generator

**Comment by sadlylegit** [comment]
try running it again

**Comment by Eevvaann6** [comment]
Only thing i get is the top changes from (Command Prompt) to (Accounts Generated: 0)

**Comment by sadlylegit** [comment]
do you have good proxies?

**Comment by Eevvaann6** [comment]
F = Fail, What proxy do you use?

**Comment by sadlylegit** [comment]
proxyscrape
