### ISSUE TITLE
[Closed] Wont work :/

### ISSUE THREAD

**Issue by Eevvaann6** [davidbaszucki/RobloxAccountGenerator#6]
C:\Users\myacc\Documents\GitHub\RobloxAccountGenerator>python account_creator.py
Traceback (most recent call last):
  File "account_creator.py", line 8, in <module>
    from funcaptcha import FunCaptchaSession, Proxy, BadGameTypeOrVariant, BannedProxy
  File "C:\Users\myacc\Documents\GitHub\RobloxAccountGenerator\funcaptcha.py", line 20, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

C:\Users\myacc\Documents\GitHub\RobloxAccountGenerator>

Script:
C:\Users\myacc\Documents\GitHub\RobloxAccountGenerator\
fp.js
Line: 1
Char: 3534
Error: 'process' is undefined
code: 800A1391
Source: Microsoft JScript runtime error

**Comment by sadlylegit** [comment]
install crypto

**Comment by Core-commits** [comment]
`pip install crypto`

**Comment by Eevvaann6** [comment]
> 
> 
> `pip install crypto`

I tried that command a while ago and i did a slightly different pip and it worked, now its doing other stuff and your not the solution because idk how to close a issue

**Comment by Core-commits** [comment]
@Eevvaann6 To close an issue just click the button "Close Issue" dont rename the title, as it still is open.
